"""CI generator: the emitted workflow must run exactly this repo's own gates."""

import json
from pathlib import Path

import yaml
from helpers import gcmd, harness

WF = Path(".github") / "workflows" / "harness.yml"


def plain_repo(tmp_path: Path, name: str) -> Path:
    """A committed git repo with harness state but no test suite, so gates come only
    from the stack manifest — realistic for a JS app or a bare python repo."""
    r = tmp_path / name
    r.mkdir()
    (r / "pyproject.toml").write_text(f'[project]\nname="{name}"\nversion="0.1.0"\n')
    gcmd(r, "init", "-q", "-b", "main")
    gcmd(r, "add", "-A")
    gcmd(r, "-c", "user.email=t@t", "-c", "user.name=t", "commit", "-qm", "i")
    assert harness(["init"], r).returncode == 0
    return r


def generated(repo: Path) -> str:
    return (repo / WF).read_text()


def test_ci_writes_workflow_from_own_gates(pyrepo: Path):
    assert harness(["init"], pyrepo).returncode == 0
    gates = json.loads((pyrepo / ".ai-engineering" / "verification.json").read_text())["gates"]
    c = harness(["ci"], pyrepo)
    assert c.returncode == 0, c.stdout + c.stderr
    y = generated(pyrepo)
    assert "Generated by `harness ci`" in y
    assert "harness scan --fail-under 70" in y
    for name, g in gates.items():
        assert f"- name: gate {name}" in y
        assert f'run: "{g["cmd"]}"' in y
    assert 'run: "pip install git+${{ secrets.HARNESS_REPO }}"' in y   # CLI comes from the ref
    assert 'run: "pip install ."' in y                                 # app deps, python fallback
    assert "setup-node" not in y                # no node stack here


def test_ci_installs_harness_from_the_repo_that_houses_it(pyrepo: Path):
    (pyrepo / "harness").mkdir()
    (pyrepo / "harness" / "cli.py").write_text("")
    assert harness(["init"], pyrepo).returncode == 0
    assert harness(["ci"], pyrepo).returncode == 0
    readiness = [s["run"] for s in yaml.safe_load(generated(pyrepo))["jobs"]["readiness"]["steps"] if "run" in s]
    assert readiness[0] == "pip install ."


def test_ci_install_override_reaches_the_readiness_job(pyrepo: Path):
    assert harness(["init"], pyrepo).returncode == 0
    ref = "pip install git+https://github.com/acme/harness.git@v1"
    assert harness(["ci", "--install", ref], pyrepo).returncode == 0
    doc = yaml.safe_load(generated(pyrepo))
    assert ref in [s["run"] for s in doc["jobs"]["readiness"]["steps"] if "run" in s]


def test_ci_honours_explicit_floor(pyrepo: Path):
    assert harness(["init"], pyrepo).returncode == 0
    assert harness(["ci", "--fail-under", "92"], pyrepo).returncode == 0
    assert "harness scan --fail-under 92" in generated(pyrepo)


def test_ci_uv_lock_installs_with_uv(tmp_path: Path):
    r = plain_repo(tmp_path, "uvapp")
    (r / "uv.lock").write_text("")
    assert harness(["ci"], r).returncode == 0
    runs = [s["run"] for s in yaml.safe_load(generated(r))["jobs"]["gates"]["steps"] if "run" in s]
    assert runs[:2] == ["pip install uv", "uv sync --frozen"]   # runners have pip, not uv


def test_ci_adds_node_setup_and_lockfile_install(tmp_path: Path):
    r = plain_repo(tmp_path, "jsapp")
    (r / "package.json").write_text(json.dumps({"scripts": {"test": "vitest run", "lint": "eslint ."}}))
    (r / "package-lock.json").write_text("{}\n")
    assert harness(["init", "--force"], r).returncode == 0
    assert harness(["ci"], r).returncode == 0
    y = generated(r)
    assert "actions/setup-node@v4" in y
    assert 'run: "npm ci --no-fund --no-audit"' in y
    assert 'run: "npm run test"' in y
    assert "- name: gate unit" in y


def test_ci_without_gates_still_runs_the_readiness_floor(tmp_path: Path):
    r = plain_repo(tmp_path, "empty")
    assert harness(["ci"], r).returncode == 0
    y = generated(r)
    assert "gate " not in y
    assert "harness scan --fail-under 70" in y


def test_ci_regenerates_its_own_file_but_never_a_handwritten_one(pyrepo: Path):
    assert harness(["init"], pyrepo).returncode == 0
    assert harness(["ci"], pyrepo).returncode == 0
    first = generated(pyrepo)
    assert harness(["ci"], pyrepo).returncode == 0
    assert generated(pyrepo) == first

    (pyrepo / WF).write_text("name: mine\n")
    refused = harness(["ci"], pyrepo)
    assert refused.returncode == 1
    assert "--force" in refused.stdout + refused.stderr
    assert generated(pyrepo) == "name: mine\n"
    assert harness(["ci", "--force"], pyrepo).returncode == 0
    assert "Generated by `harness ci`" in generated(pyrepo)


def test_ci_detects_node_app_in_a_subdir(tmp_path: Path):
    r = plain_repo(tmp_path, "mono")
    (r / "web").mkdir()
    (r / "web" / "package.json").write_text(json.dumps({"name": "web"}))
    (r / "web" / "package-lock.json").write_text("{}\n")
    (r / "web" / "node_modules" / "pkg").mkdir(parents=True)
    (r / "web" / "node_modules" / "pkg" / "package.json").write_text("{}\n")
    assert harness(["ci"], r).returncode == 0
    y = generated(r)
    assert "actions/setup-node@v4" in y
    assert 'run: "cd web && npm ci --no-fund --no-audit"' in y
    assert "node_modules" not in y


def test_ci_extra_setup_steps_run_before_the_gates(pyrepo: Path):
    assert harness(["init"], pyrepo).returncode == 0
    browsers = "cd web && npx playwright install --with-deps chromium"
    c = harness(["ci", "--setup", browsers], pyrepo)
    assert c.returncode == 0, c.stdout + c.stderr
    doc = yaml.safe_load(generated(pyrepo))
    steps = doc["jobs"]["gates"]["steps"]
    runs = [s["run"] for s in steps if "run" in s]
    assert browsers in runs
    first_gate = next(i for i, s in enumerate(steps) if str(s.get("name", "")).startswith("gate "))
    assert runs.index(browsers) < first_gate
    readiness = [s["run"] for s in doc["jobs"]["readiness"]["steps"] if "run" in s]
    assert browsers not in readiness


def test_generated_workflow_parses_as_yaml(pyrepo: Path):
    assert harness(["init"], pyrepo).returncode == 0
    assert harness(["ci"], pyrepo).returncode == 0
    doc = yaml.safe_load(generated(pyrepo))
    assert doc["name"] == "harness"
    assert doc["permissions"] == {"contents": "read"}
    assert set(doc["jobs"]) == {"readiness", "gates"}
    gates = json.loads((pyrepo / ".ai-engineering" / "verification.json").read_text())["gates"]
    readiness = [s["run"] for s in doc["jobs"]["readiness"]["steps"] if "run" in s]
    assert readiness == ["pip install git+${{ secrets.HARNESS_REPO }}", "harness scan --fail-under 70"]
    runs = [s["run"] for s in doc["jobs"]["gates"]["steps"] if "run" in s]
    assert runs == ["pip install ."] + [g["cmd"] for g in gates.values()]


def test_ci_requires_init(tmp_path: Path):
    c = harness(["ci"], tmp_path)
    assert c.returncode == 1
    assert "harness init" in c.stdout + c.stderr
