"""CI generator: a GitHub Actions workflow running the readiness floor and the repo's gates.

The YAML is generated from the repo's own verification.json, so CI and
`harness verify` execute the same commands. Re-running `harness ci` updates the
file in place (marker line); a hand-written workflow of the same name is only
touched with --force.
"""

from pathlib import Path

from harness.policy import AE, die, find_root, jload

WORKFLOW = Path(".github") / "workflows" / "harness.yml"
MARKER = "Generated by `harness ci`"
LOCKFILES = {"package-lock.json": "npm ci --no-fund --no-audit", "pnpm-lock.yaml": "pnpm install --frozen-lockfile",
             "yarn.lock": "yarn install --frozen-lockfile"}
SKIP_DIRS = {"node_modules", ".venv", "venv", "dist", "build", "test-results"}


def _manifest_dirs(r: Path) -> list[Path]:
    """Dirs holding a JS package: the root plus depth-1 app dirs (web/, frontend/…)."""
    dirs = [r] if (r / "package.json").exists() else []
    dirs += [p.parent for p in sorted(r.glob("*/package.json")) if p.parent.name not in SKIP_DIRS]
    return dirs


def _install_cmds(r: Path) -> list[str]:
    cmds = []
    if (r / "uv.lock").exists():
        cmds += ["pip install uv", "uv sync --frozen"]  # runners have pip, not uv
    for f, c in LOCKFILES.items():
        if (r / f).exists():
            cmds.append(c)
    for d in _manifest_dirs(r):
        if d == r:
            continue
        for f, c in LOCKFILES.items():
            if (d / f).exists():
                cmds.append(f"cd {d.relative_to(r).as_posix()} && {c}")
    if not cmds and (r / "pyproject.toml").exists():
        cmds.append("pip install .")
    return list(dict.fromkeys(cmds))


def _harness_install(r: Path) -> str:
    """Where CI gets the CLI: this repo when it is harness itself, otherwise a git ref
    (the package is not on PyPI; secrets.HARNESS_REPO points at the harness repository)."""
    return "pip install ." if (r / "harness" / "cli.py").exists() else "pip install git+${{ secrets.HARNESS_REPO }}"


def _yaml(r: Path, gates: dict, fail_under: int, extra: list[str], install: str) -> str:
    L = ["# " + MARKER + " — regenerate with `harness ci`; do not edit by hand.",
         "name: harness",
         "on:",
         "  pull_request:",
         "  push:",
         "    branches: [main]",
         "permissions:",
         "  contents: read",
         "jobs:",
         "  readiness:",
         "    runs-on: ubuntu-latest",
         "    steps:",
         "      - uses: actions/checkout@v4",
         "      - uses: actions/setup-python@v5",
         "        with:",
         '          python-version: "3.12"',
         f'      - run: "{install}"',
         f'      - run: "harness scan --fail-under {fail_under}"',
         "  gates:",
         "    runs-on: ubuntu-latest",
         "    steps:",
         "      - uses: actions/checkout@v4"]
    if _manifest_dirs(r):
        L += ["      - uses: actions/setup-node@v4",
              "        with:",
              '          node-version: "22"']
    if (r / "pyproject.toml").exists() or (r / "uv.lock").exists() or (r / "requirements.txt").exists():
        L += ["      - uses: actions/setup-python@v5",
              "        with:",
              '          python-version: "3.12"']
    for c in _install_cmds(r) + extra:
        L += [f'      - run: "{c}"']
    for name, g in gates.items():
        L += [f"      - name: gate {name}", f'        run: "{g["cmd"]}"']
    if not gates:
        L += ["      - name: no gates detected", "        run: \"echo 'run harness init to add gates'\""]
    return "\n".join(L) + "\n"


def cmd_ci(a) -> int:
    r = find_root(a.repo)
    if not r:
        die("run `harness init` first")
    v = jload(r / AE / "verification.json")
    dst = r / WORKFLOW
    if dst.exists() and MARKER not in dst.read_text() and not a.force:
        die(f"{WORKFLOW} is hand-written; keep it or re-run with --force")
    dst.parent.mkdir(parents=True, exist_ok=True)
    dst.write_text(_yaml(r, v.get("gates", {}), a.fail_under, a.setup or [],
                         a.install or _harness_install(r)))
    print(f"Wrote    : {WORKFLOW} ({len(v.get('gates', {}))} gates, floor {a.fail_under}) — commit it; "
          "GitHub Actions runs it on push/PR")
    return 0
