"""Core constants, versioned state-file IO, policy matching, audit, init."""

import fnmatch
import json
import os
import shutil
import sys
import time
from pathlib import Path
from typing import NoReturn

AE = ".ai-engineering"
SCHEMA = 1
LVL = {"low": 0, "medium": 1, "high": 2}
WRITE = {"Edit", "Write", "NotebookEdit"}
SAFE_ENV = (".env.example", ".env.sample", ".env.template")
META_PREFIX = (AE, ".claude", "CLAUDE.md")
ARTIFACTS = ["__pycache__/**", "*.pyc", "*.pyo", ".mypy_cache/**", ".ruff_cache/**",
             ".pytest_cache/**", "node_modules/**", ".venv/**", "*.egg-info/**",
             "test-results/**", "*/test-results/**", "playwright-report/**", "*/playwright-report/**"]


def die(m: str) -> NoReturn:
    print(f"harness: {m}", file=sys.stderr)
    sys.exit(1)


def hit(rel: str, pats: list[str]) -> bool:
    rel = rel.replace(os.sep, "/")
    for p in pats:
        if fnmatch.fnmatch(rel, p) or fnmatch.fnmatch(os.path.basename(rel), p):
            return True
        if p.endswith("/**") and (rel + "/").startswith(p[:-2]):
            return True
    return False


def find_root(start: Path | str) -> Path | None:
    d = Path(start).resolve()
    for c in [d, *d.parents]:
        if (c / AE / "policy.json").exists():
            return c
    return None


def _write_json(p: Path | str, d: dict) -> None:
    p = Path(p)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(json.dumps(d, indent=2) + "\n")


def jload(p: Path | str, versioned: bool = True) -> dict:
    d = json.loads(Path(p).read_text())
    if versioned:
        got = d.get("schema_version")
        if got != SCHEMA:
            die(f"{p}: schema_version {got!r} unsupported (need {SCHEMA}); re-run `harness init --force`")
    return d


def jsave(p: Path | str, d: dict) -> None:
    _write_json(p, {**d, "schema_version": SCHEMA})


def evaluate(pol: dict, cwd: Path, root: Path, tool: str, ti: dict) -> tuple[str | None, str]:
    """Return (decision, why); decision is 'deny', 'ask', or None (allow)."""
    fp = ti.get("file_path") or ti.get("path")
    if fp:
        ap = Path(fp) if os.path.isabs(fp) else cwd / fp
        rel = os.path.relpath(os.path.abspath(ap), root)
        if not any(rel.endswith(s) for s in SAFE_ENV):
            if hit(rel, pol["never_read"]):
                return "deny", f"{rel} is a secret path"
            if tool in WRITE and hit(rel, pol["protected"]):
                return "deny", f"{rel} is a protected path"
    c = ti.get("command")
    if c:
        for n in pol["never_commands"]:
            if n in c:
                return "deny", f"command contains forbidden pattern '{n}'"
        cc = c
        for s in SAFE_ENV:
            cc = cc.replace(s, "")
        for p in pol["never_read"]:
            t = p.rstrip("*").rstrip("/*")
            if t and t in cc:
                return "deny", f"command touches secret path '{t}'"
        for a in pol.get("ask", []):
            if a in c:
                return "ask", f"command matches ask rule '{a}'; explicit human approval required"
    return None, ""


def audit(root: Path, tool: str, target, decision: str | None, why: str) -> None:
    rec = {"t": int(time.time()), "tool": tool, "target": target,
           "decision": decision or "allow", "blocked": decision == "deny", "why": why or None}
    with open(root / AE / "audit.log", "a") as f:
        f.write(json.dumps(rec) + "\n")


def cmd_init(a) -> int:
    from harness.scan import scan
    from harness.shellx import git

    r = Path(a.repo).resolve()
    i = scan(r)
    if git(r, "rev-parse", "--git-dir")[0]:
        die("not a git repository")
    minrisk = {"typecheck": "low", "lint": "low", "unit": "low", "build": "medium", "e2e": "high"}
    jsave(r / AE / "project.json", i)
    jsave(r / AE / "verification.json",
          {"gates": {k: {"cmd": c, "min_risk": minrisk[k], **({"type": "e2e"} if k == "e2e" else {})}
                     for k, c in i["gates"].items()}, "review": True})
    pol = {"always_allow": list(i["gates"].values()) + ["git diff", "git status", "git log"],
           "ask": ["git push", "database migration", "new dependency", "edit CI", "auth changes"],
           "protected": i["protected"],
           "never_read": [".env*", "*.pem", "id_rsa*", ".ssh/**"],
           "never_commands": ["git push --force", "git push -f", "rm -rf /", "rm -rf ~", "curl | sh", "| bash",
                              "git push origin main", "git push origin master", "--no-verify"]}
    jsave(r / AE / "policy.json", pol)
    lines = ["# Project rules (generated by Harness; keep short)", "",
             f"- Stack: {', '.join(i['stacks']) or 'see repo'}", "- Verify before claiming done. Commands:"]
    lines += [f"  - {k}: `{c}`" for k, c in i["gates"].items()]
    lines += ["- Never edit protected paths: " + ", ".join(i["protected"]),
              "- Work only inside the task worktree; never push to main/master.",
              "- Done = all gates in the task contract (.ai-engineering/tasks/) pass, not 'looks right'."]
    dst = r / ("CLAUDE.md" if not (r / "CLAUDE.md").exists() or a.force else "CLAUDE.md.proposed")
    dst.write_text("\n".join(lines) + "\n")
    hw = shutil.which("harness")
    guard_cmd = f'"{hw}" guard' if hw else f'"{sys.executable}" -m harness guard'
    sp = r / ".claude" / "settings.json"
    st = jload(sp, versioned=False) if sp.exists() else {}
    perm = st.setdefault("permissions", {})
    perm["allow"] = sorted(set(perm.get("allow", []) + [f"Bash({c})" for c in pol["always_allow"]]))
    perm["deny"] = sorted(set(perm.get("deny", []) + [f"Read(./{p})" for p in pol["never_read"]]))
    hook = {"matcher": "Edit|Write|Bash|Read", "hooks": [{"type": "command", "command": guard_cmd}]}
    pre = [h for h in st.setdefault("hooks", {}).get("PreToolUse", []) if "harness" not in json.dumps(h)]
    st["hooks"]["PreToolUse"] = pre + [hook]
    _write_json(sp, st)
    print(f"Initialized {AE}/, .claude/settings.json and {dst.name} (review with `git diff`).")
    return 0
